name: course
description: A new Flutter project.

publish_to:version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.10.6'

dependencies:
  font_awesome_flutter: <10.5.0
  flutter_screenutil: ^5.7.0



  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/jonny.png
    - assets/edit.png

  uses-material-design: true


